## Módulo: Analytics Engineering

<br>

## Aula 1 - Parte 1

### Programação da Aula 1:

> ### 1. **Apresentar o formulário de pesquisa**: 
https://forms.gle/A9JnGrRYGZSJjoRe9
> ### 2. **O que são camadas especializadas**;
> ### 3. **Implementando camadas especializadas**;
> ### 4. **Desenvolvimento de exercício**;


#### Link para o formulário de Feedback da aula:
https://forms.gle/qWeiHdZZ48RHUxUL8

<div style="text-align: center;">

<br>

## Geração de camadas especializadas

<img src="https://www.databricks.com/wp-content/uploads/2019/08/Delta-Lake-Multi-Hop-Architecture-Bronze.png"  width="80%" height="60%">

###### Fonte: https://www.databricks.com/wp-content/uploads/2019/08/Delta-Lake-Multi-Hop-Architecture-Bronze.png
<br>

### Instalação das bibliotecas para conectar com o banco de dados

In [ ]:
!pip install ipython-sql
!pip install sqlalchemy
!pip install psycopg2

### Chamada da biblioteca para usar o SQL

In [ ]:
%load_ext sql

In [ ]:
from sqlalchemy import create_engine, text as sql_text
import pandas as pd
import datetime

### Configuração com as informações do banco de dados

In [ ]:
%sql postgresql://postgres:ada@localhost/ada

In [ ]:
engine = create_engine('postgresql://postgres:ada@localhost/ada')

### Primeiro comando SQL

In [ ]:
%%sql

SELECT * 

FROM first_table

### Comando SQL com o Pandas

In [ ]:
query = """
SELECT * 
FROM first_table
"""
df = pd.read_sql(sql=sql_text(query), con=engine.connect())
df

### Cria um dataframe Pandas e armazena no Banco de dados

In [ ]:
dados = {'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
         'idade': [30, 18, 67, 45, 19, 21, 25, 36, 46, 59, 72, 25, 37, 14, 59],
         'Local': ['Manaus', 'Fortaleza', 'Fortaleza', 'Sao Paulo', 'Sao Paulo', 'Belo Horizonte', 'Curitiba', 'Goiania', 'Manaus', 'Goiania', 'Belo Horizonte', 'Vitoria', 'Curitiba', 'Maceio', 'Rio de Janeiro']}

base_dados = pd.DataFrame(dados)
base_dados['load_date'] = datetime.datetime.now()
base_dados

In [ ]:
base_dados.to_sql('base_usuarios', engine, if_exists='replace', index=False)

### Criar novos dados a partir de um DataFrame Pandas e insere na tabela criada

In [ ]:
dados = {'ID': [16, 17],
         'idade': [29, 72],
         'Local': ['Belo Horizonte', 'Fortaleza']}

novos_dados = pd.DataFrame(dados)
novos_dados['load_date'] = datetime.datetime.now()
novos_dados

In [ ]:
novos_dados.to_sql('base_usuarios', engine, if_exists='append', index=False)

### API Alpha Vantage - extração de dados sobre finanças.
### Exemplo sobre a extração da série temporal dos resultados financeiros da IBM

In [ ]:
%run ./config.ipynb

In [5]:
import requests 

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=60min&apikey=8ECGDJ7MPTX3JB9W'
r = requests.get(url)
data = r.json()

data

{'Meta Data': {'1. Information': 'Intraday (60min) open, high, low, close prices and volume',
  '2. Symbol': 'IBM',
  '3. Last Refreshed': '2023-10-06 19:00:00',
  '4. Interval': '60min',
  '5. Output Size': 'Compact',
  '6. Time Zone': 'US/Eastern'},
 'Time Series (60min)': {'2023-10-06 19:00:00': {'1. open': '142.0300',
   '2. high': '142.4500',
   '3. low': '142.0300',
   '4. close': '142.0400',
   '5. volume': '438686'},
  '2023-10-06 18:00:00': {'1. open': '142.0900',
   '2. high': '142.2000',
   '3. low': '142.0300',
   '4. close': '142.2000',
   '5. volume': '438610'},
  '2023-10-06 17:00:00': {'1. open': '142.0300',
   '2. high': '142.2000',
   '3. low': '142.0100',
   '4. close': '142.2000',
   '5. volume': '1519'},
  '2023-10-06 16:00:00': {'1. open': '142.0200',
   '2. high': '142.4500',
   '3. low': '141.6900',
   '4. close': '142.4000',
   '5. volume': '1441590'},
  '2023-10-06 15:00:00': {'1. open': '142.7200',
   '2. high': '142.7400',
   '3. low': '141.9400',
   '4. close': '142.0200',
   '5. volume': '999874'},
  '2023-10-06 14:00:00': {'1. open': '142.3800',
   '2. high': '142.9400',
   '3. low': '142.3200',
   '4. close': '142.7300',
   '5. volume': '240346'},
  '2023-10-06 13:00:00': {'1. open': '141.9900',
   '2. high': '142.6800',
   '3. low': '141.9850',
   '4. close': '142.3900',
   '5. volume': '241062'},
  '2023-10-06 12:00:00': {'1. open': '142.4000',
   '2. high': '142.5100',
   '3. low': '141.8500',
   '4. close': '141.9350',
   '5. volume': '272909'},
  '2023-10-06 11:00:00': {'1. open': '141.1850',
   '2. high': '142.4100',
   '3. low': '141.1500',
   '4. close': '142.3600',
   '5. volume': '335985'},
  '2023-10-06 10:00:00': {'1. open': '140.6900',
   '2. high': '141.3800',
   '3. low': '140.1100',
   '4. close': '141.1700',
   '5. volume': '691785'},
  '2023-10-06 09:00:00': {'1. open': '140.7100',
   '2. high': '141.4500',
   '3. low': '140.2200',
   '4. close': '140.6850',
   '5. volume': '160208'},
  '2023-10-06 08:00:00': {'1. open': '141.5800',
   '2. high': '141.7000',
   '3. low': '140.2400',
   '4. close': '140.7500',
   '5. volume': '1575'},
  '2023-10-06 07:00:00': {'1. open': '141.5900',
   '2. high': '141.7000',
   '3. low': '141.5400',
   '4. close': '141.7000',
   '5. volume': '371'},
  '2023-10-06 06:00:00': {'1. open': '141.2400',
   '2. high': '141.6800',
   '3. low': '141.2400',
   '4. close': '141.5300',
   '5. volume': '176'},
  '2023-10-06 05:00:00': {'1. open': '141.5200',
   '2. high': '141.6100',
   '3. low': '141.5200',
   '4. close': '141.6000',
   '5. volume': '7'},
  '2023-10-06 04:00:00': {'1. open': '141.7000',
   '2. high': '141.7000',
   '3. low': '141.7000',
   '4. close': '141.7000',
   '5. volume': '1000'},
  '2023-10-05 19:00:00': {'1. open': '141.5200',
   '2. high': '141.5200',
   '3. low': '141.1100',
   '4. close': '141.5000',
   '5. volume': '796259'},
  '2023-10-05 18:00:00': {'1. open': '141.4800',
   '2. high': '141.5200',
   '3. low': '140.9200',
   '4. close': '141.5200',
   '5. volume': '798695'},
  '2023-10-05 17:00:00': {'1. open': '141.3000',
   '2. high': '141.5000',
   '3. low': '141.0100',
   '4. close': '141.0100',
   '5. volume': '378'},
  '2023-10-05 16:00:00': {'1. open': '141.5200',
   '2. high': '141.5200',
   '3. low': '141.1600',
   '4. close': '141.5000',
   '5. volume': '2591487'},
  '2023-10-05 15:00:00': {'1. open': '141.6400',
   '2. high': '141.7000',
   '3. low': '141.3000',
   '4. close': '141.5200',
   '5. volume': '726001'},
  '2023-10-05 14:00:00': {'1. open': '141.4500',
   '2. high': '141.6900',
   '3. low': '141.3800',
   '4. close': '141.6400',
   '5. volume': '275617'},
  '2023-10-05 13:00:00': {'1. open': '140.8800',
   '2. high': '141.5600',
   '3. low': '140.7600',
   '4. close': '141.4400',
   '5. volume': '256181'},
  '2023-10-05 12:00:00': {'1. open': '140.3300',
   '2. high': '140.8900',
   '3. low': '140.1900',
   '4. close': '140.8600',
   '5. volume': '252763'},
  '2023-10-05 11:00:00': {'1. open': '140.4800',
   '2. high': '140.6000',
   '3. low': '140.2750',
   '4. close': '140.3370',
   '5. volume': '260604'},
  '2023-10-05 10:00:00': {'1. open': '141.1350',
   '2. high': '141.2710',
   '3. low': '140.5000',
   '4. close': '140.5000',
   '5. volume': '291643'},
  '2023-10-05 09:00:00': {'1. open': '140.9200',
   '2. high': '141.3000',
   '3. low': '140.6300',
   '4. close': '141.1300',
   '5. volume': '159429'},
  '2023-10-05 08:00:00': {'1. open': '141.2400',
   '2. high': '141.5200',
   '3. low': '140.6000',
   '4. close': '140.7700',
   '5. volume': '1554'},
  '2023-10-05 07:00:00': {'1. open': '141.0500',
   '2. high': '141.2500',
   '3. low': '140.7200',
   '4. close': '141.2500',
   '5. volume': '430'},
  '2023-10-05 05:00:00': {'1. open': '141.0100',
   '2. high': '141.0100',
   '3. low': '141.0100',
   '4. close': '141.0100',
   '5. volume': '2'},
  '2023-10-05 04:00:00': {'1. open': '140.9200',
   '2. high': '141.0700',
   '3. low': '140.7000',
   '4. close': '140.7000',
   '5. volume': '32'},
  '2023-10-04 19:00:00': {'1. open': '141.0700',
   '2. high': '141.0700',
   '3. low': '140.9200',
   '4. close': '141.0600',
   '5. volume': '452484'},
  '2023-10-04 18:00:00': {'1. open': '141.0500',
   '2. high': '141.0700',
   '3. low': '141.0500',
   '4. close': '141.0700',
   '5. volume': '452301'},
  '2023-10-04 17:00:00': {'1. open': '141.0700',
   '2. high': '141.0700',
   '3. low': '141.0600',
   '4. close': '141.0600',
   '5. volume': '50'},
  '2023-10-04 16:00:00': {'1. open': '141.0700',
   '2. high': '141.3300',
   '3. low': '140.6000',
   '4. close': '140.9300',
   '5. volume': '1543392'},
  '2023-10-04 15:00:00': {'1. open': '140.7400',
   '2. high': '141.2000',
   '3. low': '140.6700',
   '4. close': '141.0700',
   '5. volume': '618636'},
  '2023-10-04 14:00:00': {'1. open': '140.4400',
   '2. high': '140.8000',
   '3. low': '140.3000',
   '4. close': '140.7200',
   '5. volume': '179083'},
  '2023-10-04 13:00:00': {'1. open': '140.8100',
   '2. high': '140.8550',
   '3. low': '140.4400',
   '4. close': '140.4400',
   '5. volume': '151139'},
  '2023-10-04 12:00:00': {'1. open': '141.0700',
   '2. high': '141.0700',
   '3. low': '140.7300',
   '4. close': '140.8200',
   '5. volume': '185099'},
  '2023-10-04 11:00:00': {'1. open': '140.1200',
   '2. high': '141.0900',
   '3. low': '140.0600',
   '4. close': '141.0520',
   '5. volume': '274589'},
  '2023-10-04 10:00:00': {'1. open': '140.2700',
   '2. high': '140.4400',
   '3. low': '139.9900',
   '4. close': '140.1300',
   '5. volume': '299959'},
  '2023-10-04 09:00:00': {'1. open': '140.8600',
   '2. high': '140.8600',
   '3. low': '140.1000',
   '4. close': '140.2700',
   '5. volume': '295922'},
  '2023-10-04 08:00:00': {'1. open': '140.4050',
   '2. high': '140.8600',
   '3. low': '139.7700',
   '4. close': '140.4500',
   '5. volume': '784'},
  '2023-10-04 07:00:00': {'1. open': '140.4100',
   '2. high': '140.5200',
   '3. low': '140.4100',
   '4. close': '140.5000',
   '5. volume': '291'},
  '2023-10-04 06:00:00': {'1. open': '140.4100',
   '2. high': '141.0300',
   '3. low': '140.4100',
   '4. close': '140.4200',
   '5. volume': '66'},
  '2023-10-04 05:00:00': {'1. open': '140.3700',
   '2. high': '140.5500',
   '3. low': '140.1400',
   '4. close': '140.2400',
   '5. volume': '31'},
  '2023-10-04 04:00:00': {'1. open': '140.3800',
   '2. high': '140.7900',
   '3. low': '139.9300',
   '4. close': '140.6100',
   '5. volume': '173'},
  '2023-10-03 19:00:00': {'1. open': '140.3900',
   '2. high': '140.3900',
   '3. low': '140.1000',
   '4. close': '140.2400',
   '5. volume': '375980'},
  '2023-10-03 18:00:00': {'1. open': '140.3800',
   '2. high': '140.3900',
   '3. low': '140.1000',
   '4. close': '140.2400',
   '5. volume': '376965'},
  '2023-10-03 17:00:00': {'1. open': '140.3200',
   '2. high': '140.9200',
   '3. low': '140.0000',
   '4. close': '140.3800',
   '5. volume': '108'},
  '2023-10-03 16:00:00': {'1. open': '140.4000',
   '2. high': '140.5000',
   '3. low': '139.7900',
   '4. close': '140.0500',
   '5. volume': '1279638'},
  '2023-10-03 15:00:00': {'1. open': '140.1500',
   '2. high': '140.4000',
   '3. low': '140.0000',
   '4. close': '140.4000',
   '5. volume': '707104'},
  '2023-10-03 14:00:00': {'1. open': '140.5530',
   '2. high': '140.5700',
   '3. low': '140.1800',
   '4. close': '140.1800',
   '5. volume': '359589'},
  '2023-10-03 13:00:00': {'1. open': '140.5900',
   '2. high': '140.9100',
   '3. low': '140.4550',
   '4. close': '140.5600',
   '5. volume': '326804'},
  '2023-10-03 12:00:00': {'1. open': '140.4500',
   '2. high': '140.7500',
   '3. low': '140.4200',
   '4. close': '140.5800',
   '5. volume': '288595'},
  '2023-10-03 11:00:00': {'1. open': '140.2000',
   '2. high': '140.5180',
   '3. low': '140.0600',
   '4. close': '140.4400',
   '5. volume': '407100'},
  '2023-10-03 10:00:00': {'1. open': '141.3200',
   '2. high': '141.4100',
   '3. low': '140.0000',
   '4. close': '140.2100',
   '5. volume': '444947'},
  '2023-10-03 09:00:00': {'1. open': '140.2500',
   '2. high': '141.6400',
   '3. low': '140.2000',
   '4. close': '141.3400',
   '5. volume': '219733'},
  '2023-10-03 08:00:00': {'1. open': '140.8000',
   '2. high': '140.8600',
   '3. low': '140.0000',
   '4. close': '140.2500',
   '5. volume': '1222'},
  '2023-10-03 07:00:00': {'1. open': '140.9600',
   '2. high': '140.9600',
   '3. low': '140.3800',
   '4. close': '140.3800',
   '5. volume': '200'},
  '2023-10-03 06:00:00': {'1. open': '141.1700',
   '2. high': '141.2300',
   '3. low': '140.8000',
   '4. close': '141.2300',
   '5. volume': '12'},
  '2023-10-03 05:00:00': {'1. open': '140.8700',
   '2. high': '140.8700',
   '3. low': '140.8700',
   '4. close': '140.8700',
   '5. volume': '3'},
  '2023-10-03 04:00:00': {'1. open': '141.1700',
   '2. high': '141.1700',
   '3. low': '140.8300',
   '4. close': '140.8300',
   '5. volume': '15'},
  '2023-10-02 19:00:00': {'1. open': '140.8000',
   '2. high': '140.9900',
   '3. low': '140.6000',
   '4. close': '140.9900',
   '5. volume': '463940'},
  '2023-10-02 18:00:00': {'1. open': '140.8000',
   '2. high': '141.0000',
   '3. low': '140.8000',
   '4. close': '141.0000',
   '5. volume': '464119'},
  '2023-10-02 17:00:00': {'1. open': '141.0000',
   '2. high': '141.0000',
   '3. low': '140.5800',
   '4. close': '140.9800',
   '5. volume': '140'},
  '2023-10-02 16:00:00': {'1. open': '140.8100',
   '2. high': '141.3800',
   '3. low': '140.1000',
   '4. close': '140.8700',
   '5. volume': '1574991'},
  '2023-10-02 15:00:00': {'1. open': '140.7000',
   '2. high': '140.9200',
   '3. low': '140.5300',
   '4. close': '140.8100',
   '5. volume': '738257'},
  '2023-10-02 14:00:00': {'1. open': '140.8500',
   '2. high': '141.3200',
   '3. low': '140.5600',
   '4. close': '140.7000',
   '5. volume': '342568'},
  '2023-10-02 13:00:00': {'1. open': '140.7300',
   '2. high': '141.2900',
   '3. low': '140.7100',
   '4. close': '140.8500',
   '5. volume': '269635'},
  '2023-10-02 12:00:00': {'1. open': '140.4300',
   '2. high': '140.7900',
   '3. low': '140.2500',
   '4. close': '140.7300',
   '5. volume': '196767'},
  '2023-10-02 11:00:00': {'1. open': '140.3100',
   '2. high': '140.9700',
   '3. low': '140.2700',
   '4. close': '140.4200',
   '5. volume': '255119'},
  '2023-10-02 10:00:00': {'1. open': '141.0500',
   '2. high': '141.2400',
   '3. low': '140.2700',
   '4. close': '140.3100',
   '5. volume': '335439'},
  '2023-10-02 09:00:00': {'1. open': '140.2800',
   '2. high': '141.4500',
   '3. low': '139.8600',
   '4. close': '141.0500',
   '5. volume': '483112'},
  '2023-10-02 08:00:00': {'1. open': '140.5700',
   '2. high': '141.3600',
   '3. low': '139.9000',
   '4. close': '140.3000',
   '5. volume': '2927'},
  '2023-10-02 07:00:00': {'1. open': '140.3200',
   '2. high': '140.5500',
   '3. low': '140.1100',
   '4. close': '140.1100',
   '5. volume': '1925'},
  '2023-10-02 06:00:00': {'1. open': '140.3500',
   '2. high': '140.7000',
   '3. low': '140.3500',
   '4. close': '140.3900',
   '5. volume': '36'},
  '2023-10-02 05:00:00': {'1. open': '140.9000',
   '2. high': '141.0200',
   '3. low': '140.4600',
   '4. close': '140.7000',
   '5. volume': '1087'},
  '2023-10-02 04:00:00': {'1. open': '140.7500',
   '2. high': '141.4600',
   '3. low': '140.7500',
   '4. close': '141.0000',
   '5. volume': '1844'},
  '2023-09-29 19:00:00': {'1. open': '140.3000',
   '2. high': '140.5900',
   '3. low': '140.0900',
   '4. close': '140.3000',
   '5. volume': '1109963'},
  '2023-09-29 18:00:00': {'1. open': '140.3000',
   '2. high': '140.4800',
   '3. low': '140.1000',
   '4. close': '140.3000',
   '5. volume': '1110560'},
  '2023-09-29 17:00:00': {'1. open': '140.4700',
   '2. high': '140.8800',
   '3. low': '140.3000',
   '4. close': '140.3300',
   '5. volume': '17348'},
  '2023-09-29 16:00:00': {'1. open': '140.3400',
   '2. high': '141.2500',
   '3. low': '139.9000',
   '4. close': '140.4800',
   '5. volume': '3579991'},
  '2023-09-29 15:00:00': {'1. open': '140.4200',
   '2. high': '140.6500',
   '3. low': '139.9700',
   '4. close': '140.3400',
   '5. volume': '1232057'},
  '2023-09-29 14:00:00': {'1. open': '139.7000',
   '2. high': '140.4050',
   '3. low': '139.6500',
   '4. close': '140.3900',
   '5. volume': '511054'},
  '2023-09-29 13:00:00': {'1. open': '140.4200',
   '2. high': '140.4200',
   '3. low': '139.6100',
   '4. close': '139.7100',
   '5. volume': '486733'},
  '2023-09-29 12:00:00': {'1. open': '140.5600',
   '2. high': '140.9600',
   '3. low': '140.3400',
   '4. close': '140.4250',
   '5. volume': '444146'},
  '2023-09-29 11:00:00': {'1. open': '141.4600',
   '2. high': '141.5200',
   '3. low': '140.4700',
   '4. close': '140.5650',
   '5. volume': '526265'},
  '2023-09-29 10:00:00': {'1. open': '141.7800',
   '2. high': '141.8600',
   '3. low': '141.2300',
   '4. close': '141.4700',
   '5. volume': '673145'},
  '2023-09-29 09:00:00': {'1. open': '142.2300',
   '2. high': '142.3500',
   '3. low': '140.8800',
   '4. close': '141.7800',
   '5. volume': '450032'},
  '2023-09-29 08:00:00': {'1. open': '141.9800',
   '2. high': '142.4500',
   '3. low': '141.5250',
   '4. close': '142.2300',
   '5. volume': '2246'},
  '2023-09-29 07:00:00': {'1. open': '142.0000',
   '2. high': '142.0800',
   '3. low': '141.9000',
   '4. close': '141.9000',
   '5. volume': '1450'},
  '2023-09-29 06:00:00': {'1. open': '142.0000',
   '2. high': '142.0000',
   '3. low': '142.0000',
   '4. close': '142.0000',
   '5. volume': '20'},
  '2023-09-29 04:00:00': {'1. open': '141.7400',
   '2. high': '141.9500',
   '3. low': '141.7400',
   '4. close': '141.9500',
   '5. volume': '2'},
  '2023-09-28 19:00:00': {'1. open': '141.5800',
   '2. high': '141.7000',
   '3. low': '141.5800',
   '4. close': '141.7000',
   '5. volume': '567846'},
  '2023-09-28 18:00:00': {'1. open': '141.6400',
   '2. high': '141.7000',
   '3. low': '141.5800',
   '4. close': '141.6500',
   '5. volume': '567792'},
  '2023-09-28 17:00:00': {'1. open': '141.7000',
   '2. high': '141.7000',
   '3. low': '141.5800',
   '4. close': '141.5800',
   '5. volume': '4486'},
  '2023-09-28 16:00:00': {'1. open': '141.5800',
   '2. high': '143.6700',
   '3. low': '141.4600',
   '4. close': '141.7000',
   '5. volume': '1969793'},
  '2023-09-28 15:00:00': {'1. open': '141.4100',
   '2. high': '141.9740',
   '3. low': '141.3700',
   '4. close': '141.5800',
   '5. volume': '1235366'},
  '2023-09-28 14:00:00': {'1. open': '141.3100',
   '2. high': '141.6600',
   '3. low': '141.2200',
   '4. close': '141.4000',
   '5. volume': '373797'}}}

### Cria um Dataframe do Pandas a partir dos dados extraídos da API

In [ ]:
import pandas as pd

dict_res = data['Time Series (60min)']

df_bronze = pd.DataFrame.from_dict(dict_res, orient='index').reset_index().rename(columns={"index": "datetime"})
df_bronze

### Prepara os tipos de cada coluna e depois armazena os resultados no banco na camada bronze

In [ ]:
import sqlalchemy as sqlal
dict_dtype={'datetime': sqlal.DateTime(), 
             '1. open':  sqlal.types.Float(precision=5, asdecimal=True),
             '2. high': sqlal.types.Float(precision=5, asdecimal=True),
             '3. low': sqlal.types.Float(precision=5, asdecimal=True),
             '4. close': sqlal.types.Float(precision=5, asdecimal=True),
             '5. volume': sqlal.types.INTEGER()}

In [ ]:
df_bronze.to_sql('ibm_prices_bronze', engine, if_exists='replace', index=False, dtype=dict_dtype)

### Leitura da tabela bronze

In [ ]:
query = """
SELECT * 
FROM ibm_prices_bronze
"""
df_silver = pd.read_sql(sql=sql_text(query), con=engine.connect())
df_silver

### Padroniza o nome das colunas da tabela bronze

In [ ]:
df_silver.columns = df_silver.columns.str.replace(r'\W', '_', regex=True)
df_silver

### Adiciona uma nova coluna calculada e efetua uma limpeza simples

In [ ]:
df_silver['diff_high_low'] = df_silver['2__high'] - df_silver['3__low'] 

df_silver = df_silver.dropna(subset=['datetime'])

values = {"1__open": 0, "2__high": 0, "3__low": 0, "4__close": 0, "5__Volumne": -1}
df_silver.fillna(value=values)
df_silver

### Define os tipos de dados e armazena os resultados como tabela silver

In [ ]:
dict_dtype={'datetime': sqlal.DateTime(), 
             '1__open':  sqlal.types.Float(precision=5, asdecimal=True),
             '2__high': sqlal.types.Float(precision=5, asdecimal=True),
             '3__low': sqlal.types.Float(precision=5, asdecimal=True),
             '4__close': sqlal.types.Float(precision=5, asdecimal=True),
             '5__volume': sqlal.types.INTEGER(),
             'diff_high_low': sqlal.types.Float(precision=5, asdecimal=True)}

In [ ]:
df_silver.to_sql('ibm_prices_silver', engine, if_exists='replace', index=False, dtype=dict_dtype)

### Leitura da tabela silver

In [ ]:
query = """
SELECT * 
FROM ibm_prices_silver
"""
df_gold = pd.read_sql(sql=sql_text(query), con=engine.connect())
df_gold

### Calcula os resultados por dia

In [ ]:
df_gold['date'] = df_gold['datetime'].dt.date
df_gold = df_gold.groupby('date').agg(max_high=("2__high", "max"), 
                                      min_low=("3__low", "min"), 
                                      mean_diff_high_low=("diff_high_low", "mean"))
df_gold

### Prepara os tipos de cada coluna e armazena os dados na camada Gold

In [ ]:
dict_dtype={'date': sqlal.Date(), 
             'max_high':  sqlal.types.Float(precision=5, asdecimal=True),
             'min_low': sqlal.types.Float(precision=5, asdecimal=True),
             'mean_diff_high_low': sqlal.types.Float(precision=5, asdecimal=True)}

In [ ]:
df_gold.to_sql('ibm_prices_gold', engine, if_exists='replace', index=True, dtype=dict_dtype)